// LOCALHOST

### GET - Display Homepage
GET http://localhost:8080/

### GET - Display All Books
GET http://localhost:8080/books

### GET - Display Book by Id (A Court of Thorns and Roses)
GET http://localhost:8080/books/673fa330e7491c357daf234c

### POST - Create Book
POST http://localhost:8080/books HTTP/1.1
Content-Type: application/json

{
    "title": "Delete Me",
    "author": "Testing",
    "isbn": "0123456789",
    "format": "fake",
    "pages": 1,
    "firstPublished": 1,
    "genre": ["none"]
}

### PUT - Update Book
### When testing add Delete Me book above first then update id in URL below
PUT http://localhost:8080/books/673fa3eab3d1d6c4579afbbe HTTP/1.1
Content-Type: application/json

{
    "title": "Still Delete Me",
    "author": "Still Testing",
    "isbn": "9876543210",
    "format": "veryFake",
    "pages": 1,
    "firstPublished": 2,
    "genre": ["none", "done"]
}

### DELETE - Delete Book
### When testing add Delete Me book above first then update id in URL below
DELETE http://localhost:8080/books/673fa3eab3d1d6c4579afbbe HTTP/1.1


// PRODUCTION

### GET - Display Homepage
GET https://cse-341-project2-ij3n.onrender.com

### GET - Display All Books
GET https://cse-341-project2-ij3n.onrender.com/books

### GET - Display Book by Id (A Court of Thorns and Roses)
GET https://cse-341-project2-ij3n.onrender.com/books/673fa330e7491c357daf234c

### POST - Create Book
POST https://cse-341-project2-ij3n.onrender.com/books HTTP/1.1
Content-Type: application/json

{
    "title": "Delete Me",
    "author": "Testing",
    "isbn": "0123456789",
    "format": "fake",
    "pages": 1,
    "firstPublished": 1,
    "genre": ["none"]
}

### PUT - Update Book
### When testing add Delete Me book above first then update id in URL below
PUT https://cse-341-project2-ij3n.onrender.com/books/673cd3c6e7713851fb9afe5e HTTP/1.1
Content-Type: application/json

{
    "title": "Still Delete Me",
    "author": "Still Testing",
    "isbn": "9876543210",
    "format": "veryFake",
    "pages": 1,
    "firstPublished": 2,
    "genre": ["none", "done"]
}

### DELETE - Delete Book
### When testing add Delete Me book above first then update id in URL below
DELETE https://cse-341-project2-ij3n.onrender.com/books/673cd3c6e7713851fb9afe5e HTTP/1.1